"""Pre-built judge demo scenarios for hackathon pitch."""

DEMO_SCENARIOS = [
    {
        "id": "ipl_chinnaswamy",
        "title": "IPL Match — Chinnaswamy Stadium",
        "subtitle": "Planned public event · 50,000+ crowd expected",
        "event_type": "planned",
        "event_cause": "public_event",
        "corridor": "CBD 2",
        "priority": "High",
        "latitude": 12.9788,
        "longitude": 77.5995,
        "junction": "QueensStatueCircle",
        "description": "Cricket Match at M Chinnaswamy Stadium. Heavy crowd expected from MG Road and Cubbon Road.",
        "requires_closure": False,
        "pitch_line": "2-hour advance warning lets BTP pre-position 10+ officers before crowd arrives.",
    },
    {
        "id": "orr_accident",
        "title": "Multi-Vehicle Accident — ORR East",
        "subtitle": "Unplanned · Peak hour cascade risk",
        "event_type": "unplanned",
        "event_cause": "accident",
        "corridor": "ORR East 1",
        "priority": "High",
        "latitude": 12.9465,
        "longitude": 77.6987,
        "junction": "Marathahalli Bridge",
        "description": "Major accident on ORR near Kadubisanahalli. Two lanes blocked, traffic backing up.",
        "requires_closure": True,
        "pitch_line": "GNN propagation predicts spillover to Whitefield Road within 45 minutes.",
    },
    {
        "id": "kannada_breakdown",
        "title": "BMTC Breakdown — Kannada NLP",
        "subtitle": "Officer report in Kannada · Auto-classified",
        "event_type": "unplanned",
        "event_cause": "vehicle_breakdown",
        "corridor": "Non-corridor",
        "priority": "High",
        "latitude": 12.9329,
        "longitude": 77.4880,
        "junction": "",
        "description": "ಬಿಎಂಟಿಸಿ ಬಸ್ ಕೆಟ್ಟು ನಿಂತಿದೆ ಸರ್",
        "requires_closure": False,
        "pitch_line": "NLP engine reads Kannada field reports — no English translation needed.",
    },
    {
        "id": "monsoon_waterlogging",
        "title": "Monsoon Waterlogging — ORR East 2",
        "subtitle": "Seasonal risk · 120 min clearance ETA",
        "event_type": "unplanned",
        "event_cause": "water_logging",
        "corridor": "ORR East 2",
        "priority": "High",
        "latitude": 13.0008,
        "longitude": 77.6814,
        "junction": "",
        "description": "Heavy water logging underpass near Whitefield Road. Lorry stuck, traffic slow moving.",
        "requires_closure": False,
        "pitch_line": "Economic impact quantifier: ₹2.3 Cr productivity loss prevented per deployment.",
    },
    {
        "id": "vip_convoy",
        "title": "VIP Movement — Bellary Road",
        "subtitle": "Protocol event · Multi-corridor impact",
        "event_type": "planned",
        "event_cause": "vip_movement",
        "corridor": "Bellary Road 1",
        "priority": "High",
        "latitude": 12.9936,
        "longitude": 77.5845,
        "junction": "Make In India Circle",
        "description": "VIP convoy movement from CM office towards Hebbal. Road closures expected.",
        "requires_closure": True,
        "pitch_line": "Fusion engine merges planned route data with live anomaly signals.",
    },
    {
        "id": "procession_festival",
        "title": "Festival Procession — Hosur Road",
        "subtitle": "Planned · Silk Board junction critical",
        "event_type": "planned",
        "event_cause": "procession",
        "corridor": "Hosur Road",
        "priority": "High",
        "latitude": 12.9169,
        "longitude": 77.6100,
        "junction": "Silk Board Junction",
        "description": "Religious procession on Hosur Road. Expected 3-hour road occupation.",
        "requires_closure": True,
        "pitch_line": "4-hour forecast timeline shows peak CRS at +90 minutes — deploy before peak.",
    },
]


def get_scenarios() -> list[dict]:
    return DEMO_SCENARIOS


def get_scenario(scenario_id: str) -> dict | None:
    return next((s for s in DEMO_SCENARIOS if s["id"] == scenario_id), None)
